name: Build and Release

on:
  push:
    branches: [dev]
    tags:
      - "v*"
  pull_request:
    branches: [dev]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: pgadmingo:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract files from Docker image
        uses: shrink/actions-docker-extract@v3
        with:
          image: pgadmingo:test
          path: /target/.
          destination: extracted-artifacts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: extracted-artifacts/
          retention-days: 7

  create-release:
    runs-on: ubuntu-latest
    needs: build
    # if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./release-artifacts

      - name: Create GitHub Release and Upload Assets
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release with unpackaged artifacts for version ${{ github.ref_name }}."
          draft: false
          prerelease: false
          files: |
            ./release-artifacts/**
